//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carents.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarentsModel1Container : DbContext
    {
        public CarentsModel1Container()
            : base("name=CarentsModel1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Permisson> Permissons { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<User_roles> User_roles { get; set; }
        public virtual DbSet<permi_car> permi_car { get; set; }
        public virtual DbSet<permi_order> permi_order { get; set; }
    }
}
