//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class permi_order
    {
        public int Id { get; set; }
        public int PermissonId { get; set; }
        public int OrderId { get; set; }
    
        public virtual Permisson Permisson { get; set; }
        public virtual Order Order { get; set; }
    }
}
