//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permisson
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Permisson()
        {
            this.permi_car = new HashSet<permi_car>();
            this.permi_order = new HashSet<permi_order>();
        }
    
        public int Id { get; set; }
        public int RolesId { get; set; }
        public string Permission_name { get; set; }
        public string permission_type { get; set; }
        public string Permission_av { get; set; }
    
        public virtual Roles Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<permi_car> permi_car { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<permi_order> permi_order { get; set; }
    }
}
