//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_roles
    {
        public int Id { get; set; }
        public int RolesId { get; set; }
        public int UserEmail { get; set; }
    
        public virtual Roles Role { get; set; }
        public virtual User User { get; set; }
    }
}
